platform:ios, '8.0'

target 'YBBaseFrameworkDemo' do

pod 'YBBaseDefine', '~>1.0.1'
pod 'YBBaseCategory', '~>1.0.1'
pod 'YBKeychainManager', '~>1.0.1'
pod 'YBLoginWindowManager', '~>1.0.1'
pod 'AFNetworking', '~>3.1.0'
pod 'SVProgressHUD', '~>2.1.2'

end
